<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: c2c_interface.proto

namespace CnukServer\C2C;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>CnukServer.C2C.Request</code>
 */
class Request extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.CnukServer.Header.Request header = 1;</code>
     */
    private $header = null;
    /**
     * Generated from protobuf field <code>int64 creat_time = 2;</code>
     */
    private $creat_time = 0;
    /**
     * Generated from protobuf field <code>int64 end_time = 3;</code>
     */
    private $end_time = 0;
    /**
     * Generated from protobuf field <code>string order_num = 4;</code>
     */
    private $order_num = '';
    /**
     * Generated from protobuf field <code>string user_id = 5;</code>
     */
    private $user_id = '';
    /**
     * Generated from protobuf field <code>string acquire_user_id = 6;</code>
     */
    private $acquire_user_id = '';
    /**
     * Generated from protobuf field <code>string currency = 7;</code>
     */
    private $currency = '';
    /**
     * Generated from protobuf field <code>string fee_id = 8;</code>
     */
    private $fee_id = '';
    /**
     * Generated from protobuf field <code>string amount = 9;</code>
     */
    private $amount = '';
    /**
     * Generated from protobuf field <code>int64 status = 10;</code>
     */
    private $status = 0;
    /**
     * Generated from protobuf field <code>string maket_maker_ord = 11;</code>
     */
    private $maket_maker_ord = '';
    /**
     * Generated from protobuf field <code>string fee = 12;</code>
     */
    private $fee = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \CnukServer\Header\Request $header
     *     @type int|string $creat_time
     *     @type int|string $end_time
     *     @type string $order_num
     *     @type string $user_id
     *     @type string $acquire_user_id
     *     @type string $currency
     *     @type string $fee_id
     *     @type string $amount
     *     @type int|string $status
     *     @type string $maket_maker_ord
     *     @type string $fee
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\C2CInterface::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.CnukServer.Header.Request header = 1;</code>
     * @return \CnukServer\Header\Request
     */
    public function getHeader()
    {
        return $this->header;
    }

    /**
     * Generated from protobuf field <code>.CnukServer.Header.Request header = 1;</code>
     * @param \CnukServer\Header\Request $var
     * @return $this
     */
    public function setHeader($var)
    {
        GPBUtil::checkMessage($var, \CnukServer\Header\Request::class);
        $this->header = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 creat_time = 2;</code>
     * @return int|string
     */
    public function getCreatTime()
    {
        return $this->creat_time;
    }

    /**
     * Generated from protobuf field <code>int64 creat_time = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCreatTime($var)
    {
        GPBUtil::checkInt64($var);
        $this->creat_time = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 end_time = 3;</code>
     * @return int|string
     */
    public function getEndTime()
    {
        return $this->end_time;
    }

    /**
     * Generated from protobuf field <code>int64 end_time = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setEndTime($var)
    {
        GPBUtil::checkInt64($var);
        $this->end_time = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string order_num = 4;</code>
     * @return string
     */
    public function getOrderNum()
    {
        return $this->order_num;
    }

    /**
     * Generated from protobuf field <code>string order_num = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setOrderNum($var)
    {
        GPBUtil::checkString($var, True);
        $this->order_num = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string user_id = 5;</code>
     * @return string
     */
    public function getUserId()
    {
        return $this->user_id;
    }

    /**
     * Generated from protobuf field <code>string user_id = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setUserId($var)
    {
        GPBUtil::checkString($var, True);
        $this->user_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string acquire_user_id = 6;</code>
     * @return string
     */
    public function getAcquireUserId()
    {
        return $this->acquire_user_id;
    }

    /**
     * Generated from protobuf field <code>string acquire_user_id = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setAcquireUserId($var)
    {
        GPBUtil::checkString($var, True);
        $this->acquire_user_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string currency = 7;</code>
     * @return string
     */
    public function getCurrency()
    {
        return $this->currency;
    }

    /**
     * Generated from protobuf field <code>string currency = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setCurrency($var)
    {
        GPBUtil::checkString($var, True);
        $this->currency = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string fee_id = 8;</code>
     * @return string
     */
    public function getFeeId()
    {
        return $this->fee_id;
    }

    /**
     * Generated from protobuf field <code>string fee_id = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setFeeId($var)
    {
        GPBUtil::checkString($var, True);
        $this->fee_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string amount = 9;</code>
     * @return string
     */
    public function getAmount()
    {
        return $this->amount;
    }

    /**
     * Generated from protobuf field <code>string amount = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setAmount($var)
    {
        GPBUtil::checkString($var, True);
        $this->amount = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 status = 10;</code>
     * @return int|string
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Generated from protobuf field <code>int64 status = 10;</code>
     * @param int|string $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkInt64($var);
        $this->status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string maket_maker_ord = 11;</code>
     * @return string
     */
    public function getMaketMakerOrd()
    {
        return $this->maket_maker_ord;
    }

    /**
     * Generated from protobuf field <code>string maket_maker_ord = 11;</code>
     * @param string $var
     * @return $this
     */
    public function setMaketMakerOrd($var)
    {
        GPBUtil::checkString($var, True);
        $this->maket_maker_ord = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string fee = 12;</code>
     * @return string
     */
    public function getFee()
    {
        return $this->fee;
    }

    /**
     * Generated from protobuf field <code>string fee = 12;</code>
     * @param string $var
     * @return $this
     */
    public function setFee($var)
    {
        GPBUtil::checkString($var, True);
        $this->fee = $var;

        return $this;
    }

}

