<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: borrower_interface.proto

namespace GPBMetadata;

class BorrowerInterface
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Header::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0abd010a18626f72726f7765725f696e746572666163652e70726f746f12" .
            "13436e756b5365727665722e426f72726f776572224b0a07526571756573" .
            "74122a0a0668656164657218012001280b321a2e436e756b536572766572" .
            "2e4865616465722e5265717565737412140a0c6f726465725f6e756d6265" .
            "7218032001280922370a08526573706f6e7365122b0a0668656164657218" .
            "012001280b321b2e436e756b5365727665722e4865616465722e52657370" .
            "6f6e7365620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

