<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: c2c_interface.proto

namespace GPBMetadata;

class C2CInterface
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Header::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0af7020a136332635f696e746572666163652e70726f746f120e436e756b" .
            "5365727665722e433243228e020a0752657175657374122a0a0668656164" .
            "657218012001280b321a2e436e756b5365727665722e4865616465722e52" .
            "65717565737412120a0a63726561745f74696d6518022001280312110a09" .
            "6f726465725f6e756d180420012809120f0a07757365725f696418052001" .
            "280912170a0f616371756972655f757365725f696418062001280912100a" .
            "0863757272656e6379180720012809120e0a066665655f69641808200128" .
            "09120e0a06616d6f756e74180920012809120e0a06737461747573180a20" .
            "012803120b0a03666565180c20012809120d0a056d6f6e6579180d200128" .
            "09120f0a076164735f6f7264180e2001280912170a0f6d61726b65745f6d" .
            "616b65725f6964180f2001280922370a08526573706f6e7365122b0a0668" .
            "656164657218012001280b321b2e436e756b5365727665722e4865616465" .
            "722e526573706f6e7365620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

