<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: c2c_interface.proto

namespace GPBMetadata;

class C2CInterface
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Header::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0ae9020a136332635f696e746572666163652e70726f746f120e436e756b" .
            "5365727665722e4332432280020a0752657175657374122a0a0668656164" .
            "657218012001280b321a2e436e756b5365727665722e4865616465722e52" .
            "65717565737412120a0a63726561745f74696d6518022001280312100a08" .
            "656e645f74696d6518032001280312110a096f726465725f6e756d180420" .
            "012809120f0a07757365725f696418052001280912170a0f616371756972" .
            "655f757365725f696418062001280912100a0863757272656e6379180720" .
            "012809120e0a066665655f6964180820012809120e0a06616d6f756e7418" .
            "0920012809120e0a06737461747573180a2001280312170a0f6d616b6574" .
            "5f6d616b65725f6f7264180b20012809120b0a03666565180c2001280922" .
            "370a08526573706f6e7365122b0a0668656164657218012001280b321b2e" .
            "436e756b5365727665722e4865616465722e526573706f6e736562067072" .
            "6f746f33"
        ));

        static::$is_initialized = true;
    }
}

