<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: confir_withdrawal_interface.proto

namespace GPBMetadata;

class ConfirWithdrawalInterface
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Header::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0ae2010a21636f6e6669725f7769746864726177616c5f696e7465726661" .
            "63652e70726f746f1219436e756b5365727665722e57616c6c657443616c" .
            "6c6261636b22610a0752657175657374122a0a0668656164657218012001" .
            "280b321a2e436e756b5365727665722e4865616465722e52657175657374" .
            "12140a0c6f726465725f6e756d62657218022001280912140a0c6f726465" .
            "725f73746174757318032001280422370a08526573706f6e7365122b0a06" .
            "68656164657218012001280b321b2e436e756b5365727665722e48656164" .
            "65722e526573706f6e7365620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

