<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: deposit_interface.proto

namespace GPBMetadata;

class DepositInterface
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Header::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0ad0020a176465706f7369745f696e746572666163652e70726f746f1212" .
            "436e756b5365727665722e4465706f73697422df010a0752657175657374" .
            "122a0a0668656164657218012001280b321a2e436e756b5365727665722e" .
            "4865616465722e5265717565737412140a0c6f726465725f6e756d626572" .
            "180220012809120f0a07757365725f6964180320012804120f0a07636f69" .
            "6e5f6964180420012804120e0a067372635f6964180520012804120c0a04" .
            "72617465180620012809120e0a06616d6f756e74180720012809120e0a06" .
            "696e636f6d65180820012809120c0a0474786964180920012809120c0a04" .
            "74797065180a2001280412160a0e736f757263655f6163636f756e74180b" .
            "2001280922370a08526573706f6e7365122b0a0668656164657218012001" .
            "280b321b2e436e756b5365727665722e4865616465722e526573706f6e73" .
            "65620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

