<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: deposit_interface.proto

namespace GPBMetadata;

class DepositInterface
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Header::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0abb010a176465706f7369745f696e746572666163652e70726f746f1212" .
            "436e756b5365727665722e4465706f736974224b0a075265717565737412" .
            "2a0a0668656164657218012001280b321a2e436e756b5365727665722e48" .
            "65616465722e5265717565737412140a0c6f726465725f6e756d62657218" .
            "022001280922370a08526573706f6e7365122b0a06686561646572180120" .
            "01280b321b2e436e756b5365727665722e4865616465722e526573706f6e" .
            "7365620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

