<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: exchange_interface.proto

namespace GPBMetadata;

class ExchangeInterface
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Header::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0a84030a1865786368616e67655f696e746572666163652e70726f746f12" .
            "13436e756b5365727665722e45786368616e67652291020a075265717565" .
            "7374122a0a0668656164657218012001280b321a2e436e756b5365727665" .
            "722e4865616465722e52657175657374120f0a07757365725f6964180320" .
            "01280912120a0a74726164655f70616972180520012809120e0a06616d6f" .
            "756e74180620012809120c0a0472617465180720012809120b0a03666565" .
            "18082001280912140a0c6f726465725f6e756d626572180920012809120c" .
            "0a0474797065180a20012804120f0a076665655f756964180c2001280912" .
            "0d0a05746f74616c180d2001280912160a0e63616c63756c6174655f7479" .
            "7065180e2001280412180a106d61726b657465725f6665655f7569641810" .
            "2001280912140a0c6d61726b657465725f66656518112001280922370a08" .
            "526573706f6e7365122b0a0668656164657218012001280b321b2e436e75" .
            "6b5365727665722e4865616465722e526573706f6e7365620670726f746f" .
            "33"
        ));

        static::$is_initialized = true;
    }
}

