<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: exchange_interface.proto

namespace GPBMetadata;

class ExchangeInterface
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Header::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0ad1020a1865786368616e67655f696e746572666163652e70726f746f12" .
            "13436e756b5365727665722e45786368616e676522de010a075265717565" .
            "7374122a0a0668656164657218012001280b321a2e436e756b5365727665" .
            "722e4865616465722e52657175657374120c0a0474696d65180220012804" .
            "120f0a07757365725f696418032001280912120a0a74726164655f706169" .
            "72180520012809120e0a06616d6f756e74180620012809120c0a04726174" .
            "65180720012809120b0a0366656518082001280912140a0c6f726465725f" .
            "6e756d626572180920012809120c0a0474797065180a2001280412140a0c" .
            "6f726465725f737461747573180b20012804120f0a076665655f75696418" .
            "0c2001280922370a08526573706f6e7365122b0a06686561646572180120" .
            "01280b321b2e436e756b5365727665722e4865616465722e526573706f6e" .
            "7365620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

