<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: header.proto

namespace GPBMetadata;

class Header
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ad1010a0c6865616465722e70726f746f1211436e756b5365727665722e" .
            "48656164657222160a0752657175657374120b0a0375726c180120012809" .
            "225b0a08526573706f6e7365122e0a0673746174757318012001280e321e" .
            "2e436e756b5365727665722e4865616465722e5472616465537461747573" .
            "12120a0a726573756c745f6d7367180220012809120b0a0375726c180320" .
            "0128092a310a0b547261646553746174757312080a044661696c1000120b" .
            "0a0750656e64696e671001120b0a07537563636573731002620670726f74" .
            "6f33"
        ));

        static::$is_initialized = true;
    }
}

