<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: header.proto

namespace GPBMetadata;

class Header
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0af5010a0c6865616465722e70726f746f1211436e756b5365727665722e" .
            "486561646572223a0a0752657175657374120b0a0375726c180120012809" .
            "120e0a067369676e616c18022001280912120a0a7075626c69635f6b6579" .
            "180320012809225b0a08526573706f6e7365122e0a067374617475731801" .
            "2001280e321e2e436e756b5365727665722e4865616465722e5472616465" .
            "53746174757312120a0a726573756c745f6d7367180220012809120b0a03" .
            "75726c1803200128092a310a0b547261646553746174757312080a044661" .
            "696c1000120b0a0750656e64696e671001120b0a07537563636573731002" .
            "620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

