<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: heart_beat_interface.proto

namespace GPBMetadata;

class HeartBeatInterface
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Header::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0abc010a1a68656172745f626561745f696e746572666163652e70726f74" .
            "6f1214436e756b5365727665722e48656172744265617422350a07526571" .
            "75657374122a0a0668656164657218012001280b321a2e436e756b536572" .
            "7665722e4865616465722e5265717565737422490a08526573706f6e7365" .
            "122b0a0668656164657218012001280b321b2e436e756b5365727665722e" .
            "4865616465722e526573706f6e736512100a0874696d6574656d70180220" .
            "012804620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

