<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: reimburse_interface.proto

namespace GPBMetadata;

class ReimburseInterface
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Header::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0acf010a197265696d62757273655f696e746572666163652e70726f746f" .
            "1214436e756b5365727665722e5265696d6275727365225b0a0752657175" .
            "657374122a0a0668656164657218012001280b321a2e436e756b53657276" .
            "65722e4865616465722e52657175657374120a0a02696418022001280412" .
            "180a10636f6e6669726d5f61646d696e5f696418032001280422370a0852" .
            "6573706f6e7365122b0a0668656164657218012001280b321b2e436e756b" .
            "5365727665722e4865616465722e526573706f6e7365620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

