<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: statistic_client_interface.proto

namespace GPBMetadata;

class StatisticClientInterface
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a8e020a207374617469737469635f636c69656e745f696e746572666163" .
            "652e70726f746f121a436e756b5365727665722e53746174697374696343" .
            "6c69656e7422170a0752657175657374120c0a0474696d65180120012804" .
            "22ac010a08526573706f6e736512160a0e636c69656e745f636f6e6e6563" .
            "7418012001280812120a0a73656e645f627974657318022001280412120a" .
            "0a726563765f627974657318032001280412140a0c726571756573745f63" .
            "6f737418042001280412120a0a73656e645f636f756e7418052001280312" .
            "100a0873656e645f65727218062001280312120a0a726563765f636f756e" .
            "7418072001280312100a08726563765f657272180820012803620670726f" .
            "746f33"
        ));

        static::$is_initialized = true;
    }
}

