<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transfer_interface.proto

namespace GPBMetadata;

class TransferInterface
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Header::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0add020a187472616e736665725f696e746572666163652e70726f746f12" .
            "13436e756b5365727665722e5472616e7366657222ea010a075265717565" .
            "7374122a0a0668656164657218012001280b321a2e436e756b5365727665" .
            "722e4865616465722e52657175657374120f0a077061795f756964180320" .
            "01280912120a0a6163717569725f75696418042001280912120a0a747261" .
            "64655f70616972180520012809120e0a06616d6f756e7418062001280912" .
            "0b0a03666565180720012809120c0a047479706518082001280412140a0c" .
            "6f726465725f6e756d62657218092001280912140a0c6f726465725f7374" .
            "61747573180a20012804120f0a076665655f756964180b2001280912120a" .
            "0a6f726465725f74797065180c2001280422370a08526573706f6e736512" .
            "2b0a0668656164657218012001280b321b2e436e756b5365727665722e48" .
            "65616465722e526573706f6e7365620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

