<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transfer_interface.proto

namespace GPBMetadata;

class TransferInterface
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Header::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0ad7020a187472616e736665725f696e746572666163652e70726f746f12" .
            "13436e756b5365727665722e5472616e7366657222e4010a075265717565" .
            "7374122a0a0668656164657218012001280b321a2e436e756b5365727665" .
            "722e4865616465722e52657175657374120c0a0474696d65180220012804" .
            "120f0a077061795f75696418032001280912120a0a6163717569725f7569" .
            "6418042001280912120a0a74726164655f70616972180520012809120e0a" .
            "06616d6f756e74180620012809120b0a03666565180720012809120c0a04" .
            "7479706518082001280412140a0c6f726465725f6e756d62657218092001" .
            "280912140a0c6f726465725f737461747573180a20012804120f0a076665" .
            "655f756964180b2001280922370a08526573706f6e7365122b0a06686561" .
            "64657218012001280b321b2e436e756b5365727665722e4865616465722e" .
            "526573706f6e7365620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

