<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: visa_interface.proto

namespace GPBMetadata;

class VisaInterface
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Header::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0ad3010a14766973615f696e746572666163652e70726f746f120f436e75" .
            "6b5365727665722e5669736122580a0752657175657374122a0a06686561" .
            "64657218012001280b321a2e436e756b5365727665722e4865616465722e" .
            "52657175657374120f0a07757365725f696418022001280412100a086375" .
            "7272656e637918032001280922480a08526573706f6e7365122b0a066865" .
            "6164657218012001280b321b2e436e756b5365727665722e486561646572" .
            "2e526573706f6e7365120f0a0762616c616e636518022001280962067072" .
            "6f746f33"
        ));

        static::$is_initialized = true;
    }
}

