<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: withdrawal_interface.proto

namespace GPBMetadata;

class WithdrawalInterface
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Header::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0af8020a1a7769746864726177616c5f696e746572666163652e70726f74" .
            "6f1215436e756b5365727665722e5769746864726177616c2281020a0752" .
            "657175657374122a0a0668656164657218012001280b321a2e436e756b53" .
            "65727665722e4865616465722e52657175657374120f0a07757365725f69" .
            "64180220012809120c0a0474696d65180320012804121a0a127061795f77" .
            "616c6c65745f61646472657373180520012809121e0a1661637175697265" .
            "5f77616c6c65745f6164647265737318062001280912150a0d6375727265" .
            "6e63795f6e616d65180720012809120e0a06616d6f756e74180820012809" .
            "120b0a0366656518092001280912140a0c6f726465725f6e756d62657218" .
            "0a2001280912140a0c6f726465725f737461747573180b20012804120f0a" .
            "076665655f756964180c2001280922370a08526573706f6e7365122b0a06" .
            "68656164657218012001280b321b2e436e756b5365727665722e48656164" .
            "65722e526573706f6e7365620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

