<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: confir_withdrawal_interface.proto

namespace CnukServer\WalletCallback;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>CnukServer.WalletCallback.Request</code>
 */
class Request extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.CnukServer.Header.Request header = 1;</code>
     */
    private $header = null;
    /**
     * Generated from protobuf field <code>string order_number = 2;</code>
     */
    private $order_number = '';
    /**
     * Generated from protobuf field <code>uint64 order_status = 3;</code>
     */
    private $order_status = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \CnukServer\Header\Request $header
     *     @type string $order_number
     *     @type int|string $order_status
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\ConfirWithdrawalInterface::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.CnukServer.Header.Request header = 1;</code>
     * @return \CnukServer\Header\Request
     */
    public function getHeader()
    {
        return $this->header;
    }

    /**
     * Generated from protobuf field <code>.CnukServer.Header.Request header = 1;</code>
     * @param \CnukServer\Header\Request $var
     * @return $this
     */
    public function setHeader($var)
    {
        GPBUtil::checkMessage($var, \CnukServer\Header\Request::class);
        $this->header = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string order_number = 2;</code>
     * @return string
     */
    public function getOrderNumber()
    {
        return $this->order_number;
    }

    /**
     * Generated from protobuf field <code>string order_number = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setOrderNumber($var)
    {
        GPBUtil::checkString($var, True);
        $this->order_number = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 order_status = 3;</code>
     * @return int|string
     */
    public function getOrderStatus()
    {
        return $this->order_status;
    }

    /**
     * Generated from protobuf field <code>uint64 order_status = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setOrderStatus($var)
    {
        GPBUtil::checkUint64($var);
        $this->order_status = $var;

        return $this;
    }

}

