<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: statistic_client_interface.proto

namespace CnukServer\StatisticClient;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>CnukServer.StatisticClient.Response</code>
 */
class Response extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bool client_connect = 1;</code>
     */
    private $client_connect = false;
    /**
     * Generated from protobuf field <code>uint64 send_bytes = 2;</code>
     */
    private $send_bytes = 0;
    /**
     * Generated from protobuf field <code>uint64 recv_bytes = 3;</code>
     */
    private $recv_bytes = 0;
    /**
     * Generated from protobuf field <code>uint64 request_cost = 4;</code>
     */
    private $request_cost = 0;
    /**
     * Generated from protobuf field <code>int64 send_count = 5;</code>
     */
    private $send_count = 0;
    /**
     * Generated from protobuf field <code>int64 send_err = 6;</code>
     */
    private $send_err = 0;
    /**
     * Generated from protobuf field <code>int64 recv_count = 7;</code>
     */
    private $recv_count = 0;
    /**
     * Generated from protobuf field <code>int64 recv_err = 8;</code>
     */
    private $recv_err = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $client_connect
     *     @type int|string $send_bytes
     *     @type int|string $recv_bytes
     *     @type int|string $request_cost
     *     @type int|string $send_count
     *     @type int|string $send_err
     *     @type int|string $recv_count
     *     @type int|string $recv_err
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\StatisticClientInterface::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bool client_connect = 1;</code>
     * @return bool
     */
    public function getClientConnect()
    {
        return $this->client_connect;
    }

    /**
     * Generated from protobuf field <code>bool client_connect = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setClientConnect($var)
    {
        GPBUtil::checkBool($var);
        $this->client_connect = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 send_bytes = 2;</code>
     * @return int|string
     */
    public function getSendBytes()
    {
        return $this->send_bytes;
    }

    /**
     * Generated from protobuf field <code>uint64 send_bytes = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSendBytes($var)
    {
        GPBUtil::checkUint64($var);
        $this->send_bytes = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 recv_bytes = 3;</code>
     * @return int|string
     */
    public function getRecvBytes()
    {
        return $this->recv_bytes;
    }

    /**
     * Generated from protobuf field <code>uint64 recv_bytes = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setRecvBytes($var)
    {
        GPBUtil::checkUint64($var);
        $this->recv_bytes = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 request_cost = 4;</code>
     * @return int|string
     */
    public function getRequestCost()
    {
        return $this->request_cost;
    }

    /**
     * Generated from protobuf field <code>uint64 request_cost = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setRequestCost($var)
    {
        GPBUtil::checkUint64($var);
        $this->request_cost = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 send_count = 5;</code>
     * @return int|string
     */
    public function getSendCount()
    {
        return $this->send_count;
    }

    /**
     * Generated from protobuf field <code>int64 send_count = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSendCount($var)
    {
        GPBUtil::checkInt64($var);
        $this->send_count = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 send_err = 6;</code>
     * @return int|string
     */
    public function getSendErr()
    {
        return $this->send_err;
    }

    /**
     * Generated from protobuf field <code>int64 send_err = 6;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSendErr($var)
    {
        GPBUtil::checkInt64($var);
        $this->send_err = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 recv_count = 7;</code>
     * @return int|string
     */
    public function getRecvCount()
    {
        return $this->recv_count;
    }

    /**
     * Generated from protobuf field <code>int64 recv_count = 7;</code>
     * @param int|string $var
     * @return $this
     */
    public function setRecvCount($var)
    {
        GPBUtil::checkInt64($var);
        $this->recv_count = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 recv_err = 8;</code>
     * @return int|string
     */
    public function getRecvErr()
    {
        return $this->recv_err;
    }

    /**
     * Generated from protobuf field <code>int64 recv_err = 8;</code>
     * @param int|string $var
     * @return $this
     */
    public function setRecvErr($var)
    {
        GPBUtil::checkInt64($var);
        $this->recv_err = $var;

        return $this;
    }

}

