<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: heart_beat_interface.proto

namespace CnukServer\HeartBeat;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>CnukServer.HeartBeat.Response</code>
 */
class Response extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.CnukServer.Header.Response header = 1;</code>
     */
    private $header = null;
    /**
     * Generated from protobuf field <code>uint64 timetemp = 2;</code>
     */
    private $timetemp = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \CnukServer\Header\Response $header
     *     @type int|string $timetemp
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\HeartBeatInterface::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.CnukServer.Header.Response header = 1;</code>
     * @return \CnukServer\Header\Response
     */
    public function getHeader()
    {
        return $this->header;
    }

    /**
     * Generated from protobuf field <code>.CnukServer.Header.Response header = 1;</code>
     * @param \CnukServer\Header\Response $var
     * @return $this
     */
    public function setHeader($var)
    {
        GPBUtil::checkMessage($var, \CnukServer\Header\Response::class);
        $this->header = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 timetemp = 2;</code>
     * @return int|string
     */
    public function getTimetemp()
    {
        return $this->timetemp;
    }

    /**
     * Generated from protobuf field <code>uint64 timetemp = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTimetemp($var)
    {
        GPBUtil::checkUint64($var);
        $this->timetemp = $var;

        return $this;
    }

}

