<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: statistic_server_interface.proto

namespace CnukServer\StatisticServer;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>CnukServer.StatisticServer.Response</code>
 */
class Response extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.CnukServer.StatisticServer.ServiceStatistic withdrawal_submit = 1;</code>
     */
    private $withdrawal_submit = null;
    /**
     * Generated from protobuf field <code>.CnukServer.StatisticServer.ServiceStatistic withdrawal_configure = 2;</code>
     */
    private $withdrawal_configure = null;
    /**
     * Generated from protobuf field <code>.CnukServer.StatisticServer.ServiceStatistic trade = 3;</code>
     */
    private $trade = null;
    /**
     * Generated from protobuf field <code>.CnukServer.StatisticServer.WorkerThreadeStatistic trade_worker = 4;</code>
     */
    private $trade_worker = null;
    /**
     * Generated from protobuf field <code>.CnukServer.StatisticServer.ServiceStatistic transfer = 5;</code>
     */
    private $transfer = null;
    /**
     * Generated from protobuf field <code>.CnukServer.StatisticServer.WorkerThreadeStatistic transfer_worker = 6;</code>
     */
    private $transfer_worker = null;
    /**
     * Generated from protobuf field <code>.CnukServer.StatisticServer.ServiceStatistic deposit = 7;</code>
     */
    private $deposit = null;
    /**
     * Generated from protobuf field <code>.CnukServer.StatisticServer.ServiceStatistic c2c_submit = 8;</code>
     */
    private $c2c_submit = null;
    /**
     * Generated from protobuf field <code>.CnukServer.StatisticServer.ServiceStatistic c2c_configure = 9;</code>
     */
    private $c2c_configure = null;
    /**
     * Generated from protobuf field <code>.CnukServer.StatisticServer.ServiceStatistic c2c_cancle = 10;</code>
     */
    private $c2c_cancle = null;
    /**
     * Generated from protobuf field <code>.CnukServer.Header.Response header = 11;</code>
     */
    private $header = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \CnukServer\StatisticServer\ServiceStatistic $withdrawal_submit
     *     @type \CnukServer\StatisticServer\ServiceStatistic $withdrawal_configure
     *     @type \CnukServer\StatisticServer\ServiceStatistic $trade
     *     @type \CnukServer\StatisticServer\WorkerThreadeStatistic $trade_worker
     *     @type \CnukServer\StatisticServer\ServiceStatistic $transfer
     *     @type \CnukServer\StatisticServer\WorkerThreadeStatistic $transfer_worker
     *     @type \CnukServer\StatisticServer\ServiceStatistic $deposit
     *     @type \CnukServer\StatisticServer\ServiceStatistic $c2c_submit
     *     @type \CnukServer\StatisticServer\ServiceStatistic $c2c_configure
     *     @type \CnukServer\StatisticServer\ServiceStatistic $c2c_cancle
     *     @type \CnukServer\Header\Response $header
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\StatisticServerInterface::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.CnukServer.StatisticServer.ServiceStatistic withdrawal_submit = 1;</code>
     * @return \CnukServer\StatisticServer\ServiceStatistic
     */
    public function getWithdrawalSubmit()
    {
        return $this->withdrawal_submit;
    }

    /**
     * Generated from protobuf field <code>.CnukServer.StatisticServer.ServiceStatistic withdrawal_submit = 1;</code>
     * @param \CnukServer\StatisticServer\ServiceStatistic $var
     * @return $this
     */
    public function setWithdrawalSubmit($var)
    {
        GPBUtil::checkMessage($var, \CnukServer\StatisticServer\ServiceStatistic::class);
        $this->withdrawal_submit = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.CnukServer.StatisticServer.ServiceStatistic withdrawal_configure = 2;</code>
     * @return \CnukServer\StatisticServer\ServiceStatistic
     */
    public function getWithdrawalConfigure()
    {
        return $this->withdrawal_configure;
    }

    /**
     * Generated from protobuf field <code>.CnukServer.StatisticServer.ServiceStatistic withdrawal_configure = 2;</code>
     * @param \CnukServer\StatisticServer\ServiceStatistic $var
     * @return $this
     */
    public function setWithdrawalConfigure($var)
    {
        GPBUtil::checkMessage($var, \CnukServer\StatisticServer\ServiceStatistic::class);
        $this->withdrawal_configure = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.CnukServer.StatisticServer.ServiceStatistic trade = 3;</code>
     * @return \CnukServer\StatisticServer\ServiceStatistic
     */
    public function getTrade()
    {
        return $this->trade;
    }

    /**
     * Generated from protobuf field <code>.CnukServer.StatisticServer.ServiceStatistic trade = 3;</code>
     * @param \CnukServer\StatisticServer\ServiceStatistic $var
     * @return $this
     */
    public function setTrade($var)
    {
        GPBUtil::checkMessage($var, \CnukServer\StatisticServer\ServiceStatistic::class);
        $this->trade = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.CnukServer.StatisticServer.WorkerThreadeStatistic trade_worker = 4;</code>
     * @return \CnukServer\StatisticServer\WorkerThreadeStatistic
     */
    public function getTradeWorker()
    {
        return $this->trade_worker;
    }

    /**
     * Generated from protobuf field <code>.CnukServer.StatisticServer.WorkerThreadeStatistic trade_worker = 4;</code>
     * @param \CnukServer\StatisticServer\WorkerThreadeStatistic $var
     * @return $this
     */
    public function setTradeWorker($var)
    {
        GPBUtil::checkMessage($var, \CnukServer\StatisticServer\WorkerThreadeStatistic::class);
        $this->trade_worker = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.CnukServer.StatisticServer.ServiceStatistic transfer = 5;</code>
     * @return \CnukServer\StatisticServer\ServiceStatistic
     */
    public function getTransfer()
    {
        return $this->transfer;
    }

    /**
     * Generated from protobuf field <code>.CnukServer.StatisticServer.ServiceStatistic transfer = 5;</code>
     * @param \CnukServer\StatisticServer\ServiceStatistic $var
     * @return $this
     */
    public function setTransfer($var)
    {
        GPBUtil::checkMessage($var, \CnukServer\StatisticServer\ServiceStatistic::class);
        $this->transfer = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.CnukServer.StatisticServer.WorkerThreadeStatistic transfer_worker = 6;</code>
     * @return \CnukServer\StatisticServer\WorkerThreadeStatistic
     */
    public function getTransferWorker()
    {
        return $this->transfer_worker;
    }

    /**
     * Generated from protobuf field <code>.CnukServer.StatisticServer.WorkerThreadeStatistic transfer_worker = 6;</code>
     * @param \CnukServer\StatisticServer\WorkerThreadeStatistic $var
     * @return $this
     */
    public function setTransferWorker($var)
    {
        GPBUtil::checkMessage($var, \CnukServer\StatisticServer\WorkerThreadeStatistic::class);
        $this->transfer_worker = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.CnukServer.StatisticServer.ServiceStatistic deposit = 7;</code>
     * @return \CnukServer\StatisticServer\ServiceStatistic
     */
    public function getDeposit()
    {
        return $this->deposit;
    }

    /**
     * Generated from protobuf field <code>.CnukServer.StatisticServer.ServiceStatistic deposit = 7;</code>
     * @param \CnukServer\StatisticServer\ServiceStatistic $var
     * @return $this
     */
    public function setDeposit($var)
    {
        GPBUtil::checkMessage($var, \CnukServer\StatisticServer\ServiceStatistic::class);
        $this->deposit = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.CnukServer.StatisticServer.ServiceStatistic c2c_submit = 8;</code>
     * @return \CnukServer\StatisticServer\ServiceStatistic
     */
    public function getC2CSubmit()
    {
        return $this->c2c_submit;
    }

    /**
     * Generated from protobuf field <code>.CnukServer.StatisticServer.ServiceStatistic c2c_submit = 8;</code>
     * @param \CnukServer\StatisticServer\ServiceStatistic $var
     * @return $this
     */
    public function setC2CSubmit($var)
    {
        GPBUtil::checkMessage($var, \CnukServer\StatisticServer\ServiceStatistic::class);
        $this->c2c_submit = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.CnukServer.StatisticServer.ServiceStatistic c2c_configure = 9;</code>
     * @return \CnukServer\StatisticServer\ServiceStatistic
     */
    public function getC2CConfigure()
    {
        return $this->c2c_configure;
    }

    /**
     * Generated from protobuf field <code>.CnukServer.StatisticServer.ServiceStatistic c2c_configure = 9;</code>
     * @param \CnukServer\StatisticServer\ServiceStatistic $var
     * @return $this
     */
    public function setC2CConfigure($var)
    {
        GPBUtil::checkMessage($var, \CnukServer\StatisticServer\ServiceStatistic::class);
        $this->c2c_configure = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.CnukServer.StatisticServer.ServiceStatistic c2c_cancle = 10;</code>
     * @return \CnukServer\StatisticServer\ServiceStatistic
     */
    public function getC2CCancle()
    {
        return $this->c2c_cancle;
    }

    /**
     * Generated from protobuf field <code>.CnukServer.StatisticServer.ServiceStatistic c2c_cancle = 10;</code>
     * @param \CnukServer\StatisticServer\ServiceStatistic $var
     * @return $this
     */
    public function setC2CCancle($var)
    {
        GPBUtil::checkMessage($var, \CnukServer\StatisticServer\ServiceStatistic::class);
        $this->c2c_cancle = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.CnukServer.Header.Response header = 11;</code>
     * @return \CnukServer\Header\Response
     */
    public function getHeader()
    {
        return $this->header;
    }

    /**
     * Generated from protobuf field <code>.CnukServer.Header.Response header = 11;</code>
     * @param \CnukServer\Header\Response $var
     * @return $this
     */
    public function setHeader($var)
    {
        GPBUtil::checkMessage($var, \CnukServer\Header\Response::class);
        $this->header = $var;

        return $this;
    }

}

