<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: statistic_server_interface.proto

namespace CnukServer\StatisticServer;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>CnukServer.StatisticServer.Response</code>
 */
class Response extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 accept = 1;</code>
     */
    private $accept = 0;
    /**
     * Generated from protobuf field <code>int64 accept_fail = 2;</code>
     */
    private $accept_fail = 0;
    /**
     * Generated from protobuf field <code>int64 request_count = 3;</code>
     */
    private $request_count = 0;
    /**
     * Generated from protobuf field <code>int64 response_count = 4;</code>
     */
    private $response_count = 0;
    /**
     * Generated from protobuf field <code>uint64 send_bytes = 5;</code>
     */
    private $send_bytes = 0;
    /**
     * Generated from protobuf field <code>uint64 recv_bytes = 6;</code>
     */
    private $recv_bytes = 0;
    /**
     * Generated from protobuf field <code>uint64 request_cost = 7;</code>
     */
    private $request_cost = 0;
    /**
     * Generated from protobuf field <code>int64 read_err = 8;</code>
     */
    private $read_err = 0;
    /**
     * Generated from protobuf field <code>int64 send_err = 9;</code>
     */
    private $send_err = 0;
    /**
     * Generated from protobuf field <code>int64 out_of_queue = 10;</code>
     */
    private $out_of_queue = 0;
    /**
     * Generated from protobuf field <code>int64 queue_delay_cost = 11;</code>
     */
    private $queue_delay_cost = 0;
    /**
     * Generated from protobuf field <code>int64 fast_reject_after_accept = 12;</code>
     */
    private $fast_reject_after_accept = 0;
    /**
     * Generated from protobuf field <code>int64 fast_reject_after_read = 13;</code>
     */
    private $fast_reject_after_read = 0;
    /**
     * Generated from protobuf field <code>int64 worker_in_queue_time_out = 14;</code>
     */
    private $worker_in_queue_time_out = 0;
    /**
     * Generated from protobuf field <code>uint64 wait_in_inqueue = 15;</code>
     */
    private $wait_in_inqueue = 0;
    /**
     * Generated from protobuf field <code>uint64 wait_in_outqueue = 16;</code>
     */
    private $wait_in_outqueue = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $accept
     *     @type int|string $accept_fail
     *     @type int|string $request_count
     *     @type int|string $response_count
     *     @type int|string $send_bytes
     *     @type int|string $recv_bytes
     *     @type int|string $request_cost
     *     @type int|string $read_err
     *     @type int|string $send_err
     *     @type int|string $out_of_queue
     *     @type int|string $queue_delay_cost
     *     @type int|string $fast_reject_after_accept
     *     @type int|string $fast_reject_after_read
     *     @type int|string $worker_in_queue_time_out
     *     @type int|string $wait_in_inqueue
     *     @type int|string $wait_in_outqueue
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\StatisticServerInterface::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 accept = 1;</code>
     * @return int|string
     */
    public function getAccept()
    {
        return $this->accept;
    }

    /**
     * Generated from protobuf field <code>int64 accept = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setAccept($var)
    {
        GPBUtil::checkInt64($var);
        $this->accept = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 accept_fail = 2;</code>
     * @return int|string
     */
    public function getAcceptFail()
    {
        return $this->accept_fail;
    }

    /**
     * Generated from protobuf field <code>int64 accept_fail = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setAcceptFail($var)
    {
        GPBUtil::checkInt64($var);
        $this->accept_fail = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 request_count = 3;</code>
     * @return int|string
     */
    public function getRequestCount()
    {
        return $this->request_count;
    }

    /**
     * Generated from protobuf field <code>int64 request_count = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setRequestCount($var)
    {
        GPBUtil::checkInt64($var);
        $this->request_count = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 response_count = 4;</code>
     * @return int|string
     */
    public function getResponseCount()
    {
        return $this->response_count;
    }

    /**
     * Generated from protobuf field <code>int64 response_count = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setResponseCount($var)
    {
        GPBUtil::checkInt64($var);
        $this->response_count = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 send_bytes = 5;</code>
     * @return int|string
     */
    public function getSendBytes()
    {
        return $this->send_bytes;
    }

    /**
     * Generated from protobuf field <code>uint64 send_bytes = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSendBytes($var)
    {
        GPBUtil::checkUint64($var);
        $this->send_bytes = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 recv_bytes = 6;</code>
     * @return int|string
     */
    public function getRecvBytes()
    {
        return $this->recv_bytes;
    }

    /**
     * Generated from protobuf field <code>uint64 recv_bytes = 6;</code>
     * @param int|string $var
     * @return $this
     */
    public function setRecvBytes($var)
    {
        GPBUtil::checkUint64($var);
        $this->recv_bytes = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 request_cost = 7;</code>
     * @return int|string
     */
    public function getRequestCost()
    {
        return $this->request_cost;
    }

    /**
     * Generated from protobuf field <code>uint64 request_cost = 7;</code>
     * @param int|string $var
     * @return $this
     */
    public function setRequestCost($var)
    {
        GPBUtil::checkUint64($var);
        $this->request_cost = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 read_err = 8;</code>
     * @return int|string
     */
    public function getReadErr()
    {
        return $this->read_err;
    }

    /**
     * Generated from protobuf field <code>int64 read_err = 8;</code>
     * @param int|string $var
     * @return $this
     */
    public function setReadErr($var)
    {
        GPBUtil::checkInt64($var);
        $this->read_err = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 send_err = 9;</code>
     * @return int|string
     */
    public function getSendErr()
    {
        return $this->send_err;
    }

    /**
     * Generated from protobuf field <code>int64 send_err = 9;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSendErr($var)
    {
        GPBUtil::checkInt64($var);
        $this->send_err = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 out_of_queue = 10;</code>
     * @return int|string
     */
    public function getOutOfQueue()
    {
        return $this->out_of_queue;
    }

    /**
     * Generated from protobuf field <code>int64 out_of_queue = 10;</code>
     * @param int|string $var
     * @return $this
     */
    public function setOutOfQueue($var)
    {
        GPBUtil::checkInt64($var);
        $this->out_of_queue = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 queue_delay_cost = 11;</code>
     * @return int|string
     */
    public function getQueueDelayCost()
    {
        return $this->queue_delay_cost;
    }

    /**
     * Generated from protobuf field <code>int64 queue_delay_cost = 11;</code>
     * @param int|string $var
     * @return $this
     */
    public function setQueueDelayCost($var)
    {
        GPBUtil::checkInt64($var);
        $this->queue_delay_cost = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 fast_reject_after_accept = 12;</code>
     * @return int|string
     */
    public function getFastRejectAfterAccept()
    {
        return $this->fast_reject_after_accept;
    }

    /**
     * Generated from protobuf field <code>int64 fast_reject_after_accept = 12;</code>
     * @param int|string $var
     * @return $this
     */
    public function setFastRejectAfterAccept($var)
    {
        GPBUtil::checkInt64($var);
        $this->fast_reject_after_accept = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 fast_reject_after_read = 13;</code>
     * @return int|string
     */
    public function getFastRejectAfterRead()
    {
        return $this->fast_reject_after_read;
    }

    /**
     * Generated from protobuf field <code>int64 fast_reject_after_read = 13;</code>
     * @param int|string $var
     * @return $this
     */
    public function setFastRejectAfterRead($var)
    {
        GPBUtil::checkInt64($var);
        $this->fast_reject_after_read = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 worker_in_queue_time_out = 14;</code>
     * @return int|string
     */
    public function getWorkerInQueueTimeOut()
    {
        return $this->worker_in_queue_time_out;
    }

    /**
     * Generated from protobuf field <code>int64 worker_in_queue_time_out = 14;</code>
     * @param int|string $var
     * @return $this
     */
    public function setWorkerInQueueTimeOut($var)
    {
        GPBUtil::checkInt64($var);
        $this->worker_in_queue_time_out = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 wait_in_inqueue = 15;</code>
     * @return int|string
     */
    public function getWaitInInqueue()
    {
        return $this->wait_in_inqueue;
    }

    /**
     * Generated from protobuf field <code>uint64 wait_in_inqueue = 15;</code>
     * @param int|string $var
     * @return $this
     */
    public function setWaitInInqueue($var)
    {
        GPBUtil::checkUint64($var);
        $this->wait_in_inqueue = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 wait_in_outqueue = 16;</code>
     * @return int|string
     */
    public function getWaitInOutqueue()
    {
        return $this->wait_in_outqueue;
    }

    /**
     * Generated from protobuf field <code>uint64 wait_in_outqueue = 16;</code>
     * @param int|string $var
     * @return $this
     */
    public function setWaitInOutqueue($var)
    {
        GPBUtil::checkUint64($var);
        $this->wait_in_outqueue = $var;

        return $this;
    }

}

