<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: statistic_server_interface.proto

namespace CnukServer\StatisticServer;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>CnukServer.StatisticServer.ServiceStatistic</code>
 */
class ServiceStatistic extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 service_num_per_second = 1;</code>
     */
    private $service_num_per_second = 0;
    /**
     * Generated from protobuf field <code>int64 service_cost_per_second = 2;</code>
     */
    private $service_cost_per_second = 0;
    /**
     * Generated from protobuf field <code>int64 service_sucess_num = 3;</code>
     */
    private $service_sucess_num = 0;
    /**
     * Generated from protobuf field <code>int64 service_fail_num = 4;</code>
     */
    private $service_fail_num = 0;
    /**
     * Generated from protobuf field <code>int64 service_cost_per_period = 5;</code>
     */
    private $service_cost_per_period = 0;
    /**
     * Generated from protobuf field <code>uint64 service_num = 6;</code>
     */
    private $service_num = 0;
    /**
     * Generated from protobuf field <code>uint64 total_cost = 7;</code>
     */
    private $total_cost = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $service_num_per_second
     *     @type int|string $service_cost_per_second
     *     @type int|string $service_sucess_num
     *     @type int|string $service_fail_num
     *     @type int|string $service_cost_per_period
     *     @type int|string $service_num
     *     @type int|string $total_cost
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\StatisticServerInterface::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 service_num_per_second = 1;</code>
     * @return int|string
     */
    public function getServiceNumPerSecond()
    {
        return $this->service_num_per_second;
    }

    /**
     * Generated from protobuf field <code>int64 service_num_per_second = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setServiceNumPerSecond($var)
    {
        GPBUtil::checkInt64($var);
        $this->service_num_per_second = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 service_cost_per_second = 2;</code>
     * @return int|string
     */
    public function getServiceCostPerSecond()
    {
        return $this->service_cost_per_second;
    }

    /**
     * Generated from protobuf field <code>int64 service_cost_per_second = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setServiceCostPerSecond($var)
    {
        GPBUtil::checkInt64($var);
        $this->service_cost_per_second = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 service_sucess_num = 3;</code>
     * @return int|string
     */
    public function getServiceSucessNum()
    {
        return $this->service_sucess_num;
    }

    /**
     * Generated from protobuf field <code>int64 service_sucess_num = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setServiceSucessNum($var)
    {
        GPBUtil::checkInt64($var);
        $this->service_sucess_num = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 service_fail_num = 4;</code>
     * @return int|string
     */
    public function getServiceFailNum()
    {
        return $this->service_fail_num;
    }

    /**
     * Generated from protobuf field <code>int64 service_fail_num = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setServiceFailNum($var)
    {
        GPBUtil::checkInt64($var);
        $this->service_fail_num = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 service_cost_per_period = 5;</code>
     * @return int|string
     */
    public function getServiceCostPerPeriod()
    {
        return $this->service_cost_per_period;
    }

    /**
     * Generated from protobuf field <code>int64 service_cost_per_period = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setServiceCostPerPeriod($var)
    {
        GPBUtil::checkInt64($var);
        $this->service_cost_per_period = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 service_num = 6;</code>
     * @return int|string
     */
    public function getServiceNum()
    {
        return $this->service_num;
    }

    /**
     * Generated from protobuf field <code>uint64 service_num = 6;</code>
     * @param int|string $var
     * @return $this
     */
    public function setServiceNum($var)
    {
        GPBUtil::checkUint64($var);
        $this->service_num = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 total_cost = 7;</code>
     * @return int|string
     */
    public function getTotalCost()
    {
        return $this->total_cost;
    }

    /**
     * Generated from protobuf field <code>uint64 total_cost = 7;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTotalCost($var)
    {
        GPBUtil::checkUint64($var);
        $this->total_cost = $var;

        return $this;
    }

}

