<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: statistic_server_interface.proto

namespace CnukServer\StatisticServer;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>CnukServer.StatisticServer.WorkerThreadeStatistic</code>
 */
class WorkerThreadeStatistic extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 total_worker_num = 1;</code>
     */
    private $total_worker_num = 0;
    /**
     * Generated from protobuf field <code>int64 free_worker_num = 2;</code>
     */
    private $free_worker_num = 0;
    /**
     * Generated from protobuf field <code>map<int32, int32> worker_deal_count = 3;</code>
     */
    private $worker_deal_count;
    /**
     * Generated from protobuf field <code>map<int32, int32> worker_all_count = 4;</code>
     */
    private $worker_all_count;
    /**
     * Generated from protobuf field <code>map<int32, int32> task_wait_time_in_queue = 5;</code>
     */
    private $task_wait_time_in_queue;
    /**
     * Generated from protobuf field <code>map<int32, int32> total_cost = 6;</code>
     */
    private $total_cost;
    /**
     * Generated from protobuf field <code>int64 worker_cost_per_period = 7;</code>
     */
    private $worker_cost_per_period = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $total_worker_num
     *     @type int|string $free_worker_num
     *     @type array|\Google\Protobuf\Internal\MapField $worker_deal_count
     *     @type array|\Google\Protobuf\Internal\MapField $worker_all_count
     *     @type array|\Google\Protobuf\Internal\MapField $task_wait_time_in_queue
     *     @type array|\Google\Protobuf\Internal\MapField $total_cost
     *     @type int|string $worker_cost_per_period
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\StatisticServerInterface::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 total_worker_num = 1;</code>
     * @return int|string
     */
    public function getTotalWorkerNum()
    {
        return $this->total_worker_num;
    }

    /**
     * Generated from protobuf field <code>int64 total_worker_num = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTotalWorkerNum($var)
    {
        GPBUtil::checkInt64($var);
        $this->total_worker_num = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 free_worker_num = 2;</code>
     * @return int|string
     */
    public function getFreeWorkerNum()
    {
        return $this->free_worker_num;
    }

    /**
     * Generated from protobuf field <code>int64 free_worker_num = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setFreeWorkerNum($var)
    {
        GPBUtil::checkInt64($var);
        $this->free_worker_num = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>map<int32, int32> worker_deal_count = 3;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getWorkerDealCount()
    {
        return $this->worker_deal_count;
    }

    /**
     * Generated from protobuf field <code>map<int32, int32> worker_deal_count = 3;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setWorkerDealCount($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::INT32, \Google\Protobuf\Internal\GPBType::INT32);
        $this->worker_deal_count = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>map<int32, int32> worker_all_count = 4;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getWorkerAllCount()
    {
        return $this->worker_all_count;
    }

    /**
     * Generated from protobuf field <code>map<int32, int32> worker_all_count = 4;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setWorkerAllCount($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::INT32, \Google\Protobuf\Internal\GPBType::INT32);
        $this->worker_all_count = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>map<int32, int32> task_wait_time_in_queue = 5;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getTaskWaitTimeInQueue()
    {
        return $this->task_wait_time_in_queue;
    }

    /**
     * Generated from protobuf field <code>map<int32, int32> task_wait_time_in_queue = 5;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setTaskWaitTimeInQueue($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::INT32, \Google\Protobuf\Internal\GPBType::INT32);
        $this->task_wait_time_in_queue = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>map<int32, int32> total_cost = 6;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getTotalCost()
    {
        return $this->total_cost;
    }

    /**
     * Generated from protobuf field <code>map<int32, int32> total_cost = 6;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setTotalCost($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::INT32, \Google\Protobuf\Internal\GPBType::INT32);
        $this->total_cost = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 worker_cost_per_period = 7;</code>
     * @return int|string
     */
    public function getWorkerCostPerPeriod()
    {
        return $this->worker_cost_per_period;
    }

    /**
     * Generated from protobuf field <code>int64 worker_cost_per_period = 7;</code>
     * @param int|string $var
     * @return $this
     */
    public function setWorkerCostPerPeriod($var)
    {
        GPBUtil::checkInt64($var);
        $this->worker_cost_per_period = $var;

        return $this;
    }

}

