<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: withdrawal_interface.proto

namespace CnukServer\Withdrawal;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>CnukServer.Withdrawal.Request</code>
 */
class Request extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.CnukServer.Header.Request header = 1;</code>
     */
    private $header = null;
    /**
     * Generated from protobuf field <code>string user_id = 2;</code>
     */
    private $user_id = '';
    /**
     *uint64 time = 3;
     *string pay_wallet_address = 5;
     *string acquire_wallet_address = 6;
     *
     * Generated from protobuf field <code>string currency_name = 5;</code>
     */
    private $currency_name = '';
    /**
     * Generated from protobuf field <code>string amount = 6;</code>
     */
    private $amount = '';
    /**
     * Generated from protobuf field <code>string fee = 7;</code>
     */
    private $fee = '';
    /**
     * Generated from protobuf field <code>string order_number = 8;</code>
     */
    private $order_number = '';
    /**
     *uint64 order_status = 9; // initial 0 
     *
     * Generated from protobuf field <code>string fee_uid = 10;</code>
     */
    private $fee_uid = '';
    /**
     * Generated from protobuf field <code>string tx_id = 11;</code>
     */
    private $tx_id = '';
    /**
     * Generated from protobuf field <code>int64 tx_height = 12;</code>
     */
    private $tx_height = 0;
    /**
     * ukex pay 2.0 addation
     *
     * Generated from protobuf field <code>string target_addr_id = 13;</code>
     */
    private $target_addr_id = '';
    /**
     * Generated from protobuf field <code>string payment_id = 14;</code>
     */
    private $payment_id = '';
    /**
     * Generated from protobuf field <code>string wallet_addr = 15;</code>
     */
    private $wallet_addr = '';
    /**
     * Generated from protobuf field <code>string total = 16;</code>
     */
    private $total = '';
    /**
     * Generated from protobuf field <code>string third_order_number = 17;</code>
     */
    private $third_order_number = '';
    /**
     * Generated from protobuf field <code>bool is_sucessed = 18;</code>
     */
    private $is_sucessed = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \CnukServer\Header\Request $header
     *     @type string $user_id
     *     @type string $currency_name
     *          uint64 time = 3;
     *          string pay_wallet_address = 5;
     *          string acquire_wallet_address = 6;
     *     @type string $amount
     *     @type string $fee
     *     @type string $order_number
     *     @type string $fee_uid
     *          uint64 order_status = 9; // initial 0 
     *     @type string $tx_id
     *     @type int|string $tx_height
     *     @type string $target_addr_id
     *           ukex pay 2.0 addation
     *     @type string $payment_id
     *     @type string $wallet_addr
     *     @type string $total
     *     @type string $third_order_number
     *     @type bool $is_sucessed
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\WithdrawalInterface::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.CnukServer.Header.Request header = 1;</code>
     * @return \CnukServer\Header\Request
     */
    public function getHeader()
    {
        return $this->header;
    }

    /**
     * Generated from protobuf field <code>.CnukServer.Header.Request header = 1;</code>
     * @param \CnukServer\Header\Request $var
     * @return $this
     */
    public function setHeader($var)
    {
        GPBUtil::checkMessage($var, \CnukServer\Header\Request::class);
        $this->header = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string user_id = 2;</code>
     * @return string
     */
    public function getUserId()
    {
        return $this->user_id;
    }

    /**
     * Generated from protobuf field <code>string user_id = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setUserId($var)
    {
        GPBUtil::checkString($var, True);
        $this->user_id = $var;

        return $this;
    }

    /**
     *uint64 time = 3;
     *string pay_wallet_address = 5;
     *string acquire_wallet_address = 6;
     *
     * Generated from protobuf field <code>string currency_name = 5;</code>
     * @return string
     */
    public function getCurrencyName()
    {
        return $this->currency_name;
    }

    /**
     *uint64 time = 3;
     *string pay_wallet_address = 5;
     *string acquire_wallet_address = 6;
     *
     * Generated from protobuf field <code>string currency_name = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setCurrencyName($var)
    {
        GPBUtil::checkString($var, True);
        $this->currency_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string amount = 6;</code>
     * @return string
     */
    public function getAmount()
    {
        return $this->amount;
    }

    /**
     * Generated from protobuf field <code>string amount = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setAmount($var)
    {
        GPBUtil::checkString($var, True);
        $this->amount = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string fee = 7;</code>
     * @return string
     */
    public function getFee()
    {
        return $this->fee;
    }

    /**
     * Generated from protobuf field <code>string fee = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setFee($var)
    {
        GPBUtil::checkString($var, True);
        $this->fee = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string order_number = 8;</code>
     * @return string
     */
    public function getOrderNumber()
    {
        return $this->order_number;
    }

    /**
     * Generated from protobuf field <code>string order_number = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setOrderNumber($var)
    {
        GPBUtil::checkString($var, True);
        $this->order_number = $var;

        return $this;
    }

    /**
     *uint64 order_status = 9; // initial 0 
     *
     * Generated from protobuf field <code>string fee_uid = 10;</code>
     * @return string
     */
    public function getFeeUid()
    {
        return $this->fee_uid;
    }

    /**
     *uint64 order_status = 9; // initial 0 
     *
     * Generated from protobuf field <code>string fee_uid = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setFeeUid($var)
    {
        GPBUtil::checkString($var, True);
        $this->fee_uid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string tx_id = 11;</code>
     * @return string
     */
    public function getTxId()
    {
        return $this->tx_id;
    }

    /**
     * Generated from protobuf field <code>string tx_id = 11;</code>
     * @param string $var
     * @return $this
     */
    public function setTxId($var)
    {
        GPBUtil::checkString($var, True);
        $this->tx_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 tx_height = 12;</code>
     * @return int|string
     */
    public function getTxHeight()
    {
        return $this->tx_height;
    }

    /**
     * Generated from protobuf field <code>int64 tx_height = 12;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTxHeight($var)
    {
        GPBUtil::checkInt64($var);
        $this->tx_height = $var;

        return $this;
    }

    /**
     * ukex pay 2.0 addation
     *
     * Generated from protobuf field <code>string target_addr_id = 13;</code>
     * @return string
     */
    public function getTargetAddrId()
    {
        return $this->target_addr_id;
    }

    /**
     * ukex pay 2.0 addation
     *
     * Generated from protobuf field <code>string target_addr_id = 13;</code>
     * @param string $var
     * @return $this
     */
    public function setTargetAddrId($var)
    {
        GPBUtil::checkString($var, True);
        $this->target_addr_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string payment_id = 14;</code>
     * @return string
     */
    public function getPaymentId()
    {
        return $this->payment_id;
    }

    /**
     * Generated from protobuf field <code>string payment_id = 14;</code>
     * @param string $var
     * @return $this
     */
    public function setPaymentId($var)
    {
        GPBUtil::checkString($var, True);
        $this->payment_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string wallet_addr = 15;</code>
     * @return string
     */
    public function getWalletAddr()
    {
        return $this->wallet_addr;
    }

    /**
     * Generated from protobuf field <code>string wallet_addr = 15;</code>
     * @param string $var
     * @return $this
     */
    public function setWalletAddr($var)
    {
        GPBUtil::checkString($var, True);
        $this->wallet_addr = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string total = 16;</code>
     * @return string
     */
    public function getTotal()
    {
        return $this->total;
    }

    /**
     * Generated from protobuf field <code>string total = 16;</code>
     * @param string $var
     * @return $this
     */
    public function setTotal($var)
    {
        GPBUtil::checkString($var, True);
        $this->total = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string third_order_number = 17;</code>
     * @return string
     */
    public function getThirdOrderNumber()
    {
        return $this->third_order_number;
    }

    /**
     * Generated from protobuf field <code>string third_order_number = 17;</code>
     * @param string $var
     * @return $this
     */
    public function setThirdOrderNumber($var)
    {
        GPBUtil::checkString($var, True);
        $this->third_order_number = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool is_sucessed = 18;</code>
     * @return bool
     */
    public function getIsSucessed()
    {
        return $this->is_sucessed;
    }

    /**
     * Generated from protobuf field <code>bool is_sucessed = 18;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsSucessed($var)
    {
        GPBUtil::checkBool($var);
        $this->is_sucessed = $var;

        return $this;
    }

}

