<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: withdrawal_interface.proto

namespace CnukServer\Withdrawal;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>CnukServer.Withdrawal.Request</code>
 */
class Request extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.CnukServer.Header.Request header = 1;</code>
     */
    private $header = null;
    /**
     * Generated from protobuf field <code>string user_id = 2;</code>
     */
    private $user_id = '';
    /**
     * Generated from protobuf field <code>uint64 time = 3;</code>
     */
    private $time = 0;
    /**
     * Generated from protobuf field <code>string pay_wallet_address = 5;</code>
     */
    private $pay_wallet_address = '';
    /**
     * Generated from protobuf field <code>string acquire_wallet_address = 6;</code>
     */
    private $acquire_wallet_address = '';
    /**
     * Generated from protobuf field <code>string currency_name = 7;</code>
     */
    private $currency_name = '';
    /**
     * Generated from protobuf field <code>string amount = 8;</code>
     */
    private $amount = '';
    /**
     * Generated from protobuf field <code>string fee = 9;</code>
     */
    private $fee = '';
    /**
     * Generated from protobuf field <code>string order_number = 10;</code>
     */
    private $order_number = '';
    /**
     * initial 0 
     *
     * Generated from protobuf field <code>uint64 order_status = 11;</code>
     */
    private $order_status = 0;
    /**
     * Generated from protobuf field <code>string fee_uid = 12;</code>
     */
    private $fee_uid = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \CnukServer\Header\Request $header
     *     @type string $user_id
     *     @type int|string $time
     *     @type string $pay_wallet_address
     *     @type string $acquire_wallet_address
     *     @type string $currency_name
     *     @type string $amount
     *     @type string $fee
     *     @type string $order_number
     *     @type int|string $order_status
     *           initial 0 
     *     @type string $fee_uid
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\WithdrawalInterface::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.CnukServer.Header.Request header = 1;</code>
     * @return \CnukServer\Header\Request
     */
    public function getHeader()
    {
        return $this->header;
    }

    /**
     * Generated from protobuf field <code>.CnukServer.Header.Request header = 1;</code>
     * @param \CnukServer\Header\Request $var
     * @return $this
     */
    public function setHeader($var)
    {
        GPBUtil::checkMessage($var, \CnukServer\Header\Request::class);
        $this->header = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string user_id = 2;</code>
     * @return string
     */
    public function getUserId()
    {
        return $this->user_id;
    }

    /**
     * Generated from protobuf field <code>string user_id = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setUserId($var)
    {
        GPBUtil::checkString($var, True);
        $this->user_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 time = 3;</code>
     * @return int|string
     */
    public function getTime()
    {
        return $this->time;
    }

    /**
     * Generated from protobuf field <code>uint64 time = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTime($var)
    {
        GPBUtil::checkUint64($var);
        $this->time = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string pay_wallet_address = 5;</code>
     * @return string
     */
    public function getPayWalletAddress()
    {
        return $this->pay_wallet_address;
    }

    /**
     * Generated from protobuf field <code>string pay_wallet_address = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setPayWalletAddress($var)
    {
        GPBUtil::checkString($var, True);
        $this->pay_wallet_address = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string acquire_wallet_address = 6;</code>
     * @return string
     */
    public function getAcquireWalletAddress()
    {
        return $this->acquire_wallet_address;
    }

    /**
     * Generated from protobuf field <code>string acquire_wallet_address = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setAcquireWalletAddress($var)
    {
        GPBUtil::checkString($var, True);
        $this->acquire_wallet_address = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string currency_name = 7;</code>
     * @return string
     */
    public function getCurrencyName()
    {
        return $this->currency_name;
    }

    /**
     * Generated from protobuf field <code>string currency_name = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setCurrencyName($var)
    {
        GPBUtil::checkString($var, True);
        $this->currency_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string amount = 8;</code>
     * @return string
     */
    public function getAmount()
    {
        return $this->amount;
    }

    /**
     * Generated from protobuf field <code>string amount = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setAmount($var)
    {
        GPBUtil::checkString($var, True);
        $this->amount = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string fee = 9;</code>
     * @return string
     */
    public function getFee()
    {
        return $this->fee;
    }

    /**
     * Generated from protobuf field <code>string fee = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setFee($var)
    {
        GPBUtil::checkString($var, True);
        $this->fee = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string order_number = 10;</code>
     * @return string
     */
    public function getOrderNumber()
    {
        return $this->order_number;
    }

    /**
     * Generated from protobuf field <code>string order_number = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setOrderNumber($var)
    {
        GPBUtil::checkString($var, True);
        $this->order_number = $var;

        return $this;
    }

    /**
     * initial 0 
     *
     * Generated from protobuf field <code>uint64 order_status = 11;</code>
     * @return int|string
     */
    public function getOrderStatus()
    {
        return $this->order_status;
    }

    /**
     * initial 0 
     *
     * Generated from protobuf field <code>uint64 order_status = 11;</code>
     * @param int|string $var
     * @return $this
     */
    public function setOrderStatus($var)
    {
        GPBUtil::checkUint64($var);
        $this->order_status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string fee_uid = 12;</code>
     * @return string
     */
    public function getFeeUid()
    {
        return $this->fee_uid;
    }

    /**
     * Generated from protobuf field <code>string fee_uid = 12;</code>
     * @param string $var
     * @return $this
     */
    public function setFeeUid($var)
    {
        GPBUtil::checkString($var, True);
        $this->fee_uid = $var;

        return $this;
    }

}

