<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transfer_interface.proto

namespace CnukServer\Transfer;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>CnukServer.Transfer.Request</code>
 */
class Request extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.CnukServer.Header.Request header = 1;</code>
     */
    private $header = null;
    /**
     *uint64 time = 2;
     *
     * Generated from protobuf field <code>string pay_uid = 3;</code>
     */
    private $pay_uid = '';
    /**
     * Generated from protobuf field <code>string acquir_uid = 4;</code>
     */
    private $acquir_uid = '';
    /**
     * Generated from protobuf field <code>string trade_pair = 5;</code>
     */
    private $trade_pair = '';
    /**
     * Generated from protobuf field <code>string amount = 6;</code>
     */
    private $amount = '';
    /**
     * Generated from protobuf field <code>string fee = 7;</code>
     */
    private $fee = '';
    /**
     * Generated from protobuf field <code>uint64 type = 8;</code>
     */
    private $type = 0;
    /**
     * Generated from protobuf field <code>string order_number = 9;</code>
     */
    private $order_number = '';
    /**
     * Generated from protobuf field <code>uint64 order_status = 10;</code>
     */
    private $order_status = 0;
    /**
     * Generated from protobuf field <code>string fee_uid = 11;</code>
     */
    private $fee_uid = '';
    /**
     * ukex pay 2.0 addation section
     *
     * Generated from protobuf field <code>uint64 order_type = 12;</code>
     */
    private $order_type = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \CnukServer\Header\Request $header
     *     @type string $pay_uid
     *          uint64 time = 2;
     *     @type string $acquir_uid
     *     @type string $trade_pair
     *     @type string $amount
     *     @type string $fee
     *     @type int|string $type
     *     @type string $order_number
     *     @type int|string $order_status
     *     @type string $fee_uid
     *     @type int|string $order_type
     *           ukex pay 2.0 addation section
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\TransferInterface::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.CnukServer.Header.Request header = 1;</code>
     * @return \CnukServer\Header\Request
     */
    public function getHeader()
    {
        return $this->header;
    }

    /**
     * Generated from protobuf field <code>.CnukServer.Header.Request header = 1;</code>
     * @param \CnukServer\Header\Request $var
     * @return $this
     */
    public function setHeader($var)
    {
        GPBUtil::checkMessage($var, \CnukServer\Header\Request::class);
        $this->header = $var;

        return $this;
    }

    /**
     *uint64 time = 2;
     *
     * Generated from protobuf field <code>string pay_uid = 3;</code>
     * @return string
     */
    public function getPayUid()
    {
        return $this->pay_uid;
    }

    /**
     *uint64 time = 2;
     *
     * Generated from protobuf field <code>string pay_uid = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setPayUid($var)
    {
        GPBUtil::checkString($var, True);
        $this->pay_uid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string acquir_uid = 4;</code>
     * @return string
     */
    public function getAcquirUid()
    {
        return $this->acquir_uid;
    }

    /**
     * Generated from protobuf field <code>string acquir_uid = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setAcquirUid($var)
    {
        GPBUtil::checkString($var, True);
        $this->acquir_uid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string trade_pair = 5;</code>
     * @return string
     */
    public function getTradePair()
    {
        return $this->trade_pair;
    }

    /**
     * Generated from protobuf field <code>string trade_pair = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setTradePair($var)
    {
        GPBUtil::checkString($var, True);
        $this->trade_pair = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string amount = 6;</code>
     * @return string
     */
    public function getAmount()
    {
        return $this->amount;
    }

    /**
     * Generated from protobuf field <code>string amount = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setAmount($var)
    {
        GPBUtil::checkString($var, True);
        $this->amount = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string fee = 7;</code>
     * @return string
     */
    public function getFee()
    {
        return $this->fee;
    }

    /**
     * Generated from protobuf field <code>string fee = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setFee($var)
    {
        GPBUtil::checkString($var, True);
        $this->fee = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 type = 8;</code>
     * @return int|string
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Generated from protobuf field <code>uint64 type = 8;</code>
     * @param int|string $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkUint64($var);
        $this->type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string order_number = 9;</code>
     * @return string
     */
    public function getOrderNumber()
    {
        return $this->order_number;
    }

    /**
     * Generated from protobuf field <code>string order_number = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setOrderNumber($var)
    {
        GPBUtil::checkString($var, True);
        $this->order_number = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 order_status = 10;</code>
     * @return int|string
     */
    public function getOrderStatus()
    {
        return $this->order_status;
    }

    /**
     * Generated from protobuf field <code>uint64 order_status = 10;</code>
     * @param int|string $var
     * @return $this
     */
    public function setOrderStatus($var)
    {
        GPBUtil::checkUint64($var);
        $this->order_status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string fee_uid = 11;</code>
     * @return string
     */
    public function getFeeUid()
    {
        return $this->fee_uid;
    }

    /**
     * Generated from protobuf field <code>string fee_uid = 11;</code>
     * @param string $var
     * @return $this
     */
    public function setFeeUid($var)
    {
        GPBUtil::checkString($var, True);
        $this->fee_uid = $var;

        return $this;
    }

    /**
     * ukex pay 2.0 addation section
     *
     * Generated from protobuf field <code>uint64 order_type = 12;</code>
     * @return int|string
     */
    public function getOrderType()
    {
        return $this->order_type;
    }

    /**
     * ukex pay 2.0 addation section
     *
     * Generated from protobuf field <code>uint64 order_type = 12;</code>
     * @param int|string $var
     * @return $this
     */
    public function setOrderType($var)
    {
        GPBUtil::checkUint64($var);
        $this->order_type = $var;

        return $this;
    }

}

