<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: reimburse_interface.proto

namespace CnukServer\Reimburse;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>CnukServer.Reimburse.Request</code>
 */
class Request extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.CnukServer.Header.Request header = 1;</code>
     */
    private $header = null;
    /**
     * Generated from protobuf field <code>uint64 id = 2;</code>
     */
    private $id = 0;
    /**
     * Generated from protobuf field <code>uint64 confirm_admin_id = 3;</code>
     */
    private $confirm_admin_id = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \CnukServer\Header\Request $header
     *     @type int|string $id
     *     @type int|string $confirm_admin_id
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\ReimburseInterface::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.CnukServer.Header.Request header = 1;</code>
     * @return \CnukServer\Header\Request
     */
    public function getHeader()
    {
        return $this->header;
    }

    /**
     * Generated from protobuf field <code>.CnukServer.Header.Request header = 1;</code>
     * @param \CnukServer\Header\Request $var
     * @return $this
     */
    public function setHeader($var)
    {
        GPBUtil::checkMessage($var, \CnukServer\Header\Request::class);
        $this->header = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 id = 2;</code>
     * @return int|string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>uint64 id = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkUint64($var);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 confirm_admin_id = 3;</code>
     * @return int|string
     */
    public function getConfirmAdminId()
    {
        return $this->confirm_admin_id;
    }

    /**
     * Generated from protobuf field <code>uint64 confirm_admin_id = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setConfirmAdminId($var)
    {
        GPBUtil::checkUint64($var);
        $this->confirm_admin_id = $var;

        return $this;
    }

}

