<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: header.proto

namespace CnukServer\Header;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>CnukServer.Header.Response</code>
 */
class Response extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.CnukServer.Header.TradeStatus status = 1;</code>
     */
    private $status = 0;
    /**
     * if execute fail, return the failed msg of execute
     *
     * Generated from protobuf field <code>string result_msg = 2;</code>
     */
    private $result_msg = '';
    /**
     * Generated from protobuf field <code>string result_code = 3;</code>
     */
    private $result_code = '';
    /**
     * Generated from protobuf field <code>string url = 4;</code>
     */
    private $url = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $status
     *     @type string $result_msg
     *           if execute fail, return the failed msg of execute
     *     @type string $result_code
     *     @type string $url
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Header::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.CnukServer.Header.TradeStatus status = 1;</code>
     * @return int
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Generated from protobuf field <code>.CnukServer.Header.TradeStatus status = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkEnum($var, \CnukServer\Header\TradeStatus::class);
        $this->status = $var;

        return $this;
    }

    /**
     * if execute fail, return the failed msg of execute
     *
     * Generated from protobuf field <code>string result_msg = 2;</code>
     * @return string
     */
    public function getResultMsg()
    {
        return $this->result_msg;
    }

    /**
     * if execute fail, return the failed msg of execute
     *
     * Generated from protobuf field <code>string result_msg = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setResultMsg($var)
    {
        GPBUtil::checkString($var, True);
        $this->result_msg = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string result_code = 3;</code>
     * @return string
     */
    public function getResultCode()
    {
        return $this->result_code;
    }

    /**
     * Generated from protobuf field <code>string result_code = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setResultCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->result_code = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string url = 4;</code>
     * @return string
     */
    public function getUrl()
    {
        return $this->url;
    }

    /**
     * Generated from protobuf field <code>string url = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->url = $var;

        return $this;
    }

}

