<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: header.proto

namespace CnukServer\Header;

/**
 * Protobuf type <code>CnukServer.Header.TradeStatus</code>
 */
class TradeStatus
{
    /**
     * Generated from protobuf enum <code>Fail = 0;</code>
     */
    const Fail = 0;
    /**
     * Generated from protobuf enum <code>Pending = 1;</code>
     */
    const Pending = 1;
    /**
     * Generated from protobuf enum <code>Success = 2;</code>
     */
    const Success = 2;
}

