<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: reconfig_interface.proto

namespace CnukServer\Config;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>CnukServer.Config.Request</code>
 */
class Request extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.CnukServer.Header.Request header = 1;</code>
     */
    private $header = null;
    /**
     *server
     *
     * Generated from protobuf field <code>string bind_ip = 2;</code>
     */
    private $bind_ip = '';
    /**
     * Generated from protobuf field <code>uint64 port = 3;</code>
     */
    private $port = 0;
    /**
     * log
     *
     * Generated from protobuf field <code>string log_dir = 4;</code>
     */
    private $log_dir = '';
    /**
     * Generated from protobuf field <code>uint64 log_level = 5;</code>
     */
    private $log_level = 0;
    /**
     * mysql
     *
     * Generated from protobuf field <code>string mysql_address = 6;</code>
     */
    private $mysql_address = '';
    /**
     * Generated from protobuf field <code>int64 mysql_port = 7;</code>
     */
    private $mysql_port = 0;
    /**
     * Generated from protobuf field <code>string mysql_db_name = 8;</code>
     */
    private $mysql_db_name = '';
    /**
     * Generated from protobuf field <code>string mysql_db_user_name = 9;</code>
     */
    private $mysql_db_user_name = '';
    /**
     * Generated from protobuf field <code>string mysql_db_password = 10;</code>
     */
    private $mysql_db_password = '';
    /**
     * Generated from protobuf field <code>uint64 mysql_connect_max_num = 11;</code>
     */
    private $mysql_connect_max_num = 0;
    /**
     * Generated from protobuf field <code>uint64 mysql_connect_pool_wait_time = 12;</code>
     */
    private $mysql_connect_pool_wait_time = 0;
    /**
     * redis
     *
     * Generated from protobuf field <code>string redis_address = 13;</code>
     */
    private $redis_address = '';
    /**
     * Generated from protobuf field <code>uint64 redis_port = 14;</code>
     */
    private $redis_port = 0;
    /**
     * Generated from protobuf field <code>uint64 redis_connect_max_num = 15;</code>
     */
    private $redis_connect_max_num = 0;
    /**
     * Generated from protobuf field <code>uint64 redis_connect_pool_wait_time = 16;</code>
     */
    private $redis_connect_pool_wait_time = 0;
    /**
     * elasticsearch
     *
     * Generated from protobuf field <code>string es_host_url = 17;</code>
     */
    private $es_host_url = '';
    /**
     * Generated from protobuf field <code>uint64 es_time_out = 18;</code>
     */
    private $es_time_out = 0;
    /**
     * Generated from protobuf field <code>uint64 es_client_num = 19;</code>
     */
    private $es_client_num = 0;
    /**
     * Generated from protobuf field <code>uint64 es_connect_pool_wait_time = 20;</code>
     */
    private $es_connect_pool_wait_time = 0;
    /**
     * service 
     *
     * Generated from protobuf field <code>uint64 trade_service_worker_num = 21;</code>
     */
    private $trade_service_worker_num = 0;
    /**
     * Generated from protobuf field <code>uint64 transfer_service_worker_num = 22;</code>
     */
    private $transfer_service_worker_num = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \CnukServer\Header\Request $header
     *     @type string $bind_ip
     *          server
     *     @type int|string $port
     *     @type string $log_dir
     *           log
     *     @type int|string $log_level
     *     @type string $mysql_address
     *           mysql
     *     @type int|string $mysql_port
     *     @type string $mysql_db_name
     *     @type string $mysql_db_user_name
     *     @type string $mysql_db_password
     *     @type int|string $mysql_connect_max_num
     *     @type int|string $mysql_connect_pool_wait_time
     *     @type string $redis_address
     *           redis
     *     @type int|string $redis_port
     *     @type int|string $redis_connect_max_num
     *     @type int|string $redis_connect_pool_wait_time
     *     @type string $es_host_url
     *           elasticsearch
     *     @type int|string $es_time_out
     *     @type int|string $es_client_num
     *     @type int|string $es_connect_pool_wait_time
     *     @type int|string $trade_service_worker_num
     *           service 
     *     @type int|string $transfer_service_worker_num
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\ReconfigInterface::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.CnukServer.Header.Request header = 1;</code>
     * @return \CnukServer\Header\Request
     */
    public function getHeader()
    {
        return $this->header;
    }

    /**
     * Generated from protobuf field <code>.CnukServer.Header.Request header = 1;</code>
     * @param \CnukServer\Header\Request $var
     * @return $this
     */
    public function setHeader($var)
    {
        GPBUtil::checkMessage($var, \CnukServer\Header\Request::class);
        $this->header = $var;

        return $this;
    }

    /**
     *server
     *
     * Generated from protobuf field <code>string bind_ip = 2;</code>
     * @return string
     */
    public function getBindIp()
    {
        return $this->bind_ip;
    }

    /**
     *server
     *
     * Generated from protobuf field <code>string bind_ip = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setBindIp($var)
    {
        GPBUtil::checkString($var, True);
        $this->bind_ip = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 port = 3;</code>
     * @return int|string
     */
    public function getPort()
    {
        return $this->port;
    }

    /**
     * Generated from protobuf field <code>uint64 port = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setPort($var)
    {
        GPBUtil::checkUint64($var);
        $this->port = $var;

        return $this;
    }

    /**
     * log
     *
     * Generated from protobuf field <code>string log_dir = 4;</code>
     * @return string
     */
    public function getLogDir()
    {
        return $this->log_dir;
    }

    /**
     * log
     *
     * Generated from protobuf field <code>string log_dir = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setLogDir($var)
    {
        GPBUtil::checkString($var, True);
        $this->log_dir = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 log_level = 5;</code>
     * @return int|string
     */
    public function getLogLevel()
    {
        return $this->log_level;
    }

    /**
     * Generated from protobuf field <code>uint64 log_level = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setLogLevel($var)
    {
        GPBUtil::checkUint64($var);
        $this->log_level = $var;

        return $this;
    }

    /**
     * mysql
     *
     * Generated from protobuf field <code>string mysql_address = 6;</code>
     * @return string
     */
    public function getMysqlAddress()
    {
        return $this->mysql_address;
    }

    /**
     * mysql
     *
     * Generated from protobuf field <code>string mysql_address = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setMysqlAddress($var)
    {
        GPBUtil::checkString($var, True);
        $this->mysql_address = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 mysql_port = 7;</code>
     * @return int|string
     */
    public function getMysqlPort()
    {
        return $this->mysql_port;
    }

    /**
     * Generated from protobuf field <code>int64 mysql_port = 7;</code>
     * @param int|string $var
     * @return $this
     */
    public function setMysqlPort($var)
    {
        GPBUtil::checkInt64($var);
        $this->mysql_port = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string mysql_db_name = 8;</code>
     * @return string
     */
    public function getMysqlDbName()
    {
        return $this->mysql_db_name;
    }

    /**
     * Generated from protobuf field <code>string mysql_db_name = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setMysqlDbName($var)
    {
        GPBUtil::checkString($var, True);
        $this->mysql_db_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string mysql_db_user_name = 9;</code>
     * @return string
     */
    public function getMysqlDbUserName()
    {
        return $this->mysql_db_user_name;
    }

    /**
     * Generated from protobuf field <code>string mysql_db_user_name = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setMysqlDbUserName($var)
    {
        GPBUtil::checkString($var, True);
        $this->mysql_db_user_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string mysql_db_password = 10;</code>
     * @return string
     */
    public function getMysqlDbPassword()
    {
        return $this->mysql_db_password;
    }

    /**
     * Generated from protobuf field <code>string mysql_db_password = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setMysqlDbPassword($var)
    {
        GPBUtil::checkString($var, True);
        $this->mysql_db_password = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 mysql_connect_max_num = 11;</code>
     * @return int|string
     */
    public function getMysqlConnectMaxNum()
    {
        return $this->mysql_connect_max_num;
    }

    /**
     * Generated from protobuf field <code>uint64 mysql_connect_max_num = 11;</code>
     * @param int|string $var
     * @return $this
     */
    public function setMysqlConnectMaxNum($var)
    {
        GPBUtil::checkUint64($var);
        $this->mysql_connect_max_num = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 mysql_connect_pool_wait_time = 12;</code>
     * @return int|string
     */
    public function getMysqlConnectPoolWaitTime()
    {
        return $this->mysql_connect_pool_wait_time;
    }

    /**
     * Generated from protobuf field <code>uint64 mysql_connect_pool_wait_time = 12;</code>
     * @param int|string $var
     * @return $this
     */
    public function setMysqlConnectPoolWaitTime($var)
    {
        GPBUtil::checkUint64($var);
        $this->mysql_connect_pool_wait_time = $var;

        return $this;
    }

    /**
     * redis
     *
     * Generated from protobuf field <code>string redis_address = 13;</code>
     * @return string
     */
    public function getRedisAddress()
    {
        return $this->redis_address;
    }

    /**
     * redis
     *
     * Generated from protobuf field <code>string redis_address = 13;</code>
     * @param string $var
     * @return $this
     */
    public function setRedisAddress($var)
    {
        GPBUtil::checkString($var, True);
        $this->redis_address = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 redis_port = 14;</code>
     * @return int|string
     */
    public function getRedisPort()
    {
        return $this->redis_port;
    }

    /**
     * Generated from protobuf field <code>uint64 redis_port = 14;</code>
     * @param int|string $var
     * @return $this
     */
    public function setRedisPort($var)
    {
        GPBUtil::checkUint64($var);
        $this->redis_port = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 redis_connect_max_num = 15;</code>
     * @return int|string
     */
    public function getRedisConnectMaxNum()
    {
        return $this->redis_connect_max_num;
    }

    /**
     * Generated from protobuf field <code>uint64 redis_connect_max_num = 15;</code>
     * @param int|string $var
     * @return $this
     */
    public function setRedisConnectMaxNum($var)
    {
        GPBUtil::checkUint64($var);
        $this->redis_connect_max_num = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 redis_connect_pool_wait_time = 16;</code>
     * @return int|string
     */
    public function getRedisConnectPoolWaitTime()
    {
        return $this->redis_connect_pool_wait_time;
    }

    /**
     * Generated from protobuf field <code>uint64 redis_connect_pool_wait_time = 16;</code>
     * @param int|string $var
     * @return $this
     */
    public function setRedisConnectPoolWaitTime($var)
    {
        GPBUtil::checkUint64($var);
        $this->redis_connect_pool_wait_time = $var;

        return $this;
    }

    /**
     * elasticsearch
     *
     * Generated from protobuf field <code>string es_host_url = 17;</code>
     * @return string
     */
    public function getEsHostUrl()
    {
        return $this->es_host_url;
    }

    /**
     * elasticsearch
     *
     * Generated from protobuf field <code>string es_host_url = 17;</code>
     * @param string $var
     * @return $this
     */
    public function setEsHostUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->es_host_url = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 es_time_out = 18;</code>
     * @return int|string
     */
    public function getEsTimeOut()
    {
        return $this->es_time_out;
    }

    /**
     * Generated from protobuf field <code>uint64 es_time_out = 18;</code>
     * @param int|string $var
     * @return $this
     */
    public function setEsTimeOut($var)
    {
        GPBUtil::checkUint64($var);
        $this->es_time_out = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 es_client_num = 19;</code>
     * @return int|string
     */
    public function getEsClientNum()
    {
        return $this->es_client_num;
    }

    /**
     * Generated from protobuf field <code>uint64 es_client_num = 19;</code>
     * @param int|string $var
     * @return $this
     */
    public function setEsClientNum($var)
    {
        GPBUtil::checkUint64($var);
        $this->es_client_num = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 es_connect_pool_wait_time = 20;</code>
     * @return int|string
     */
    public function getEsConnectPoolWaitTime()
    {
        return $this->es_connect_pool_wait_time;
    }

    /**
     * Generated from protobuf field <code>uint64 es_connect_pool_wait_time = 20;</code>
     * @param int|string $var
     * @return $this
     */
    public function setEsConnectPoolWaitTime($var)
    {
        GPBUtil::checkUint64($var);
        $this->es_connect_pool_wait_time = $var;

        return $this;
    }

    /**
     * service 
     *
     * Generated from protobuf field <code>uint64 trade_service_worker_num = 21;</code>
     * @return int|string
     */
    public function getTradeServiceWorkerNum()
    {
        return $this->trade_service_worker_num;
    }

    /**
     * service 
     *
     * Generated from protobuf field <code>uint64 trade_service_worker_num = 21;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTradeServiceWorkerNum($var)
    {
        GPBUtil::checkUint64($var);
        $this->trade_service_worker_num = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 transfer_service_worker_num = 22;</code>
     * @return int|string
     */
    public function getTransferServiceWorkerNum()
    {
        return $this->transfer_service_worker_num;
    }

    /**
     * Generated from protobuf field <code>uint64 transfer_service_worker_num = 22;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTransferServiceWorkerNum($var)
    {
        GPBUtil::checkUint64($var);
        $this->transfer_service_worker_num = $var;

        return $this;
    }

}

