<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/header.proto

namespace GPBMetadata\Proto;

class Header
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a90020a1270726f746f2f6865616465722e70726f746f1211436e756b53" .
            "65727665722e486561646572223a0a0752657175657374120b0a0375726c" .
            "180120012809120e0a067369676e616c18022001280912120a0a7075626c" .
            "69635f6b657918032001280922700a08526573706f6e7365122e0a067374" .
            "6174757318012001280e321e2e436e756b5365727665722e486561646572" .
            "2e547261646553746174757312120a0a726573756c745f6d736718022001" .
            "280912130a0b726573756c745f636f6465180320012809120b0a0375726c" .
            "1804200128092a310a0b547261646553746174757312080a044661696c10" .
            "00120b0a0750656e64696e671001120b0a07537563636573731002620670" .
            "726f746f33"
        ));

        static::$is_initialized = true;
    }
}

