<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: deposit_interface.proto

namespace CnukServer\Deposit;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>CnukServer.Deposit.Request</code>
 */
class Request extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.CnukServer.Header.Request header = 1;</code>
     */
    private $header = null;
    /**
     * Generated from protobuf field <code>string order_number = 2;</code>
     */
    private $order_number = '';
    /**
     * ukex pay 2.0 addation section
     *
     * Generated from protobuf field <code>uint64 user_id = 3;</code>
     */
    private $user_id = 0;
    /**
     * Generated from protobuf field <code>uint64 coin_id = 4;</code>
     */
    private $coin_id = 0;
    /**
     * Generated from protobuf field <code>uint64 src_id = 5;</code>
     */
    private $src_id = 0;
    /**
     * Generated from protobuf field <code>string rate = 6;</code>
     */
    private $rate = '';
    /**
     * Generated from protobuf field <code>string amount = 7;</code>
     */
    private $amount = '';
    /**
     * Generated from protobuf field <code>string income = 8;</code>
     */
    private $income = '';
    /**
     * Generated from protobuf field <code>string txid = 9;</code>
     */
    private $txid = '';
    /**
     * Generated from protobuf field <code>uint64 type = 10;</code>
     */
    private $type = 0;
    /**
     * Generated from protobuf field <code>string source_account = 11;</code>
     */
    private $source_account = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \CnukServer\Header\Request $header
     *     @type string $order_number
     *     @type int|string $user_id
     *           ukex pay 2.0 addation section
     *     @type int|string $coin_id
     *     @type int|string $src_id
     *     @type string $rate
     *     @type string $amount
     *     @type string $income
     *     @type string $txid
     *     @type int|string $type
     *     @type string $source_account
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\DepositInterface::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.CnukServer.Header.Request header = 1;</code>
     * @return \CnukServer\Header\Request
     */
    public function getHeader()
    {
        return $this->header;
    }

    /**
     * Generated from protobuf field <code>.CnukServer.Header.Request header = 1;</code>
     * @param \CnukServer\Header\Request $var
     * @return $this
     */
    public function setHeader($var)
    {
        GPBUtil::checkMessage($var, \CnukServer\Header\Request::class);
        $this->header = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string order_number = 2;</code>
     * @return string
     */
    public function getOrderNumber()
    {
        return $this->order_number;
    }

    /**
     * Generated from protobuf field <code>string order_number = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setOrderNumber($var)
    {
        GPBUtil::checkString($var, True);
        $this->order_number = $var;

        return $this;
    }

    /**
     * ukex pay 2.0 addation section
     *
     * Generated from protobuf field <code>uint64 user_id = 3;</code>
     * @return int|string
     */
    public function getUserId()
    {
        return $this->user_id;
    }

    /**
     * ukex pay 2.0 addation section
     *
     * Generated from protobuf field <code>uint64 user_id = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUserId($var)
    {
        GPBUtil::checkUint64($var);
        $this->user_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 coin_id = 4;</code>
     * @return int|string
     */
    public function getCoinId()
    {
        return $this->coin_id;
    }

    /**
     * Generated from protobuf field <code>uint64 coin_id = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCoinId($var)
    {
        GPBUtil::checkUint64($var);
        $this->coin_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 src_id = 5;</code>
     * @return int|string
     */
    public function getSrcId()
    {
        return $this->src_id;
    }

    /**
     * Generated from protobuf field <code>uint64 src_id = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSrcId($var)
    {
        GPBUtil::checkUint64($var);
        $this->src_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string rate = 6;</code>
     * @return string
     */
    public function getRate()
    {
        return $this->rate;
    }

    /**
     * Generated from protobuf field <code>string rate = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setRate($var)
    {
        GPBUtil::checkString($var, True);
        $this->rate = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string amount = 7;</code>
     * @return string
     */
    public function getAmount()
    {
        return $this->amount;
    }

    /**
     * Generated from protobuf field <code>string amount = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setAmount($var)
    {
        GPBUtil::checkString($var, True);
        $this->amount = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string income = 8;</code>
     * @return string
     */
    public function getIncome()
    {
        return $this->income;
    }

    /**
     * Generated from protobuf field <code>string income = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setIncome($var)
    {
        GPBUtil::checkString($var, True);
        $this->income = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string txid = 9;</code>
     * @return string
     */
    public function getTxid()
    {
        return $this->txid;
    }

    /**
     * Generated from protobuf field <code>string txid = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setTxid($var)
    {
        GPBUtil::checkString($var, True);
        $this->txid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 type = 10;</code>
     * @return int|string
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Generated from protobuf field <code>uint64 type = 10;</code>
     * @param int|string $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkUint64($var);
        $this->type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string source_account = 11;</code>
     * @return string
     */
    public function getSourceAccount()
    {
        return $this->source_account;
    }

    /**
     * Generated from protobuf field <code>string source_account = 11;</code>
     * @param string $var
     * @return $this
     */
    public function setSourceAccount($var)
    {
        GPBUtil::checkString($var, True);
        $this->source_account = $var;

        return $this;
    }

}

