<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: exchange_interface.proto

namespace CnukServer\Exchange;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>CnukServer.Exchange.Response</code>
 */
class Response extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.CnukServer.Header.Response header = 1;</code>
     */
    private $header = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \CnukServer\Header\Response $header
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\ExchangeInterface::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.CnukServer.Header.Response header = 1;</code>
     * @return \CnukServer\Header\Response
     */
    public function getHeader()
    {
        return $this->header;
    }

    /**
     * Generated from protobuf field <code>.CnukServer.Header.Response header = 1;</code>
     * @param \CnukServer\Header\Response $var
     * @return $this
     */
    public function setHeader($var)
    {
        GPBUtil::checkMessage($var, \CnukServer\Header\Response::class);
        $this->header = $var;

        return $this;
    }

}

